In [4]:
!pip install numpy
!pip install pandas

In [30]:
import pandas as pd
import numpy as np

In [26]:
data = {
    "Kolom1" : [10,30, None, 10],
    "Kolom2" : ["Benar", "Salah", "Benar", None],
    "Data" : [10,23,23,4]
}

In [27]:
df = pd.DataFrame(data)

In [13]:
df

Kolom1 Kolom2  Data
0    10.0  Benar    10
1    30.0  Salah    23
2     NaN  Benar    23
3    10.0   None     4

In [14]:
df.isnull().sum()

Kolom1    1
Kolom2    1
Data      0
dtype: int64

In [15]:
df.isna().sum()

Kolom1    1
Kolom2    1
Data      0
dtype: int64

In [17]:
df["Kolom1"].isna().sum()

1

In [28]:
df2 = df.copy()

In [23]:
df2["Kolom1"] = df2["Kolom1"].fillna(0)

In [24]:
df2

Kolom1 Kolom2  Data
0    10.0  Benar    10
1    30.0  Salah    23
2     0.0  Benar    23
3    10.0   None     4

In [29]:
df

Kolom1 Kolom2  Data
0    10.0  Benar    10
1    30.0  Salah    23
2     NaN  Benar    23
3    10.0   None     4

In [31]:
rata_rata = np.nanmean(df["Kolom1"], axis = 0)
print(rata_rata)

16.666666666666668


In [32]:
df["Kolom1"] = df["Kolom1"].fillna(rata_rata)

In [33]:
df

Kolom1 Kolom2  Data
0  10.000000  Benar    10
1  30.000000  Salah    23
2  16.666667  Benar    23
3  10.000000   None     4

In [38]:
modus = df["Kolom2"].mode()[0]

In [39]:
df["Kolom2"] = df["Kolom2"].fillna(modus)

In [40]:
df

Kolom1 Kolom2  Data
0  10.000000  Benar    10
1  30.000000  Salah    23
2  16.666667  Benar    23
3  10.000000  Benar     4

In [41]:
df3 = df.copy()

In [42]:
df_onehot = pd.get_dummies(df, columns=["Kolom2"])

In [43]:
df_onehot

Kolom1  Data  Kolom2_Benar  Kolom2_Salah
0  10.000000    10             1             0
1  30.000000    23             0             1
2  16.666667    23             1             0
3  10.000000     4             1             0

In [44]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

df3["Kolom2"] = label_encoder.fit_transform(df3["Kolom2"])

In [45]:
df3

Kolom1  Kolom2  Data
0  10.000000       0    10
1  30.000000       1    23
2  16.666667       0    23
3  10.000000       0     4

In [46]:
data = {
    "Kolom1" : [10,30, None, 10,10],
    "Kolom2" : ["Benar", "Salah", "Benar", None, "Benar"],
    "Data" : [10,23,23,4,10]
}

In [47]:
df5 = pd.DataFrame(data)

In [48]:
df5

Kolom1 Kolom2  Data
0    10.0  Benar    10
1    30.0  Salah    23
2     NaN  Benar    23
3    10.0   None     4
4    10.0  Benar    10

In [49]:
df5 = df5.drop_duplicates()

In [50]:
df5

Kolom1 Kolom2  Data
0    10.0  Benar    10
1    30.0  Salah    23
2     NaN  Benar    23
3    10.0   None     4

In [51]:
file_path = "/content/drive/MyDrive/ML-ISTTS/kc_house_data.csv"

In [53]:
df_data = pd.read_csv(file_path)
df_data

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [55]:
df_filter = df_data[['price','bedrooms','bathrooms']]

In [56]:
df_filter

price  bedrooms  bathrooms
0      221900.0         3       1.00
1      538000.0         3       2.25
2      180000.0         2       1.00
3      604000.0         4       3.00
4      510000.0         3       2.00
...         ...       ...        ...
21608  360000.0         3       2.50
21609  400000.0         4       2.50
21610  402101.0         2       0.75
21611  400000.0         3       2.50
21612  325000.0         2       0.75

[21613 rows x 3 columns]

In [57]:
df_new = df_data.iloc[:,2:]

In [58]:
df_new

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0      221900.0         3       1.00         1180      5650     1.0   
1      538000.0         3       2.25         2570      7242     2.0   
2      180000.0         2       1.00          770     10000     1.0   
3      604000.0         4       3.00         1960      5000     1.0   
4      510000.0         3       2.00         1680      8080     1.0   
...         ...       ...        ...          ...       ...     ...   
21608  360000.0         3       2.50         1530      1131     3.0   
21609  400000.0         4       2.50         2310      5813     2.0   
21610  402101.0         2       0.75         1020      1350     2.0   
21611  400000.0         3       2.50         1600      2388     2.0   
21612  325000.0         2       0.75         1020      1076     2.0   

       waterfront  view  condition  grade  sqft_above  sqft_basement  \
0               0     0          3      7        1180              0   
1               0     0          3      7        2170            400   
2               0     0          3      6         770              0   
3               0     0          5      7        1050            910   
4               0     0          3      8        1680              0   
...           ...   ...        ...    ...         ...            ...   
21608           0     0          3      8        1530              0   
21609           0     0          3      8        2310              0   
21610           0     0          3      7        1020              0   
21611           0     0          3      8        1600              0   
21612           0     0          3      7        1020              0   

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0          1955             0    98178  47.5112 -122.257           1340   
1          1951          1991    98125  47.7210 -122.319           1690   
2          1933             0    98028  47.7379 -122.233           2720   
3          1965             0    98136  47.5208 -122.393           1360   
4          1987             0    98074  47.6168 -122.045           1800   
...         ...           ...      ...      ...      ...            ...   
21608      2009             0    98103  47.6993 -122.346           1530   
21609      2014             0    98146  47.5107 -122.362           1830   
21610      2009             0    98144  47.5944 -122.299           1020   
21611      2004             0    98027  47.5345 -122.069           1410   
21612      2008             0    98144  47.5941 -122.299           1020   

       sqft_lot15  
0            5650  
1            7639  
2            8062  
3            5000  
4            7503  
...           ...  
21608        1509  
21609        7200  
21610        2007  
21611        1287  
21612        1357  

[21613 rows x 19 columns]

In [62]:
y = df_new["price"].values
X = df_new.iloc[:,1:].values

In [63]:
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.3)

In [66]:
len(X_train)

15129

In [67]:
len(X_test)

6484

In [68]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)


LinearRegression()

In [70]:
model.coef_

array([-3.54467418e+04,  4.57957292e+04,  1.09173799e+02,  1.41086375e-01,
        3.04011989e+03,  6.08232316e+05,  5.28318264e+04,  2.49403045e+04,
        9.50459399e+04,  7.36298827e+01,  3.55439167e+01, -2.63231963e+03,
        1.64458204e+01, -6.40323272e+02,  6.10890042e+05, -2.28892533e+05,
        2.11998585e+01, -3.75571585e-01])

In [71]:
y_hat = model.predict(X_test)

In [72]:
y_hat[0:10]

array([ 370348.26657899,  353527.56620973,  351870.90186139,
        873507.38266713,  712224.5547089 ,  482634.95948681,
       1613684.54229758,  336176.45821794,  596495.36753567,
        294001.71057599])

In [73]:
y_test[0:10]

array([ 325000.,  374950.,  395000.,  780000.,  428040.,  629000.,
       1600000.,  299995.,  470000.,  275000.])

In [74]:
from sklearn.metrics import mean_squared_error

mse_score = mean_squared_error(y_test,y_hat)

In [75]:
print("MSE : ", mse_score)

MSE :  38568766740.87369


In [80]:
y = df_new["price"].values
X = df_new.iloc[:,1:].values

In [87]:
from sklearn.preprocessing import StandardScaler
scaler_model = StandardScaler()
X = scaler_model.fit_transform(X)

In [ ]:
scaler_model.mean_

In [88]:
y_scaled = y.reshape(-1,1)

In [89]:
y_scaler_model = StandardScaler()
y = y_scaler_model.fit_transform(y_scaled).reshape(-1)

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.3)

In [91]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [93]:
y_hat = model.predict(X_test)
mse_score = mean_squared_error(y_test,y_hat)
print("MSE : ", mse_score)

MSE :  0.3548156542579545


In [96]:
y_scaler_model.inverse_transform(y_hat[0:10].reshape(-1,1))

array([[793619.85174904],
       [314454.49114269],
       [149566.6292343 ],
       [441171.13177898],
       [777782.92188146],
       [603194.11473496],
       [347820.77813656],
       [425387.81311802],
       [365349.78798439],
       [624831.8843855 ]])

In [98]:
y_scaler_model.inverse_transform(y_test[0:10].reshape(-1,1))

array([[825000.],
       [470000.],
       [235000.],
       [528000.],
       [740000.],
       [409124.],
       [452500.],
       [449999.],
       [352000.],
       [425000.]])

In [108]:
from sklearn.preprocessing import PolynomialFeatures

features_builder = PolynomialFeatures(degree=2, include_bias = True)
polynomial_features = features_builder.fit_transform(X)


In [109]:
X_train, X_test, y_train, y_test = train_test_split(polynomial_features,y , test_size=0.3)

In [110]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [111]:
y_hat = model.predict(X_test)
mse_score = mean_squared_error(y_test,y_hat)
print("MSE : ", mse_score)

MSE :  0.1799131418408701
